export const EMOJI_LIST = [
  { emoji: '🔗', name: 'link' },
  // Geek & Gaming
  { emoji: '🤓', name: 'nerd face' },
  { emoji: '👾', name: 'alien monster' },
  { emoji: '🎮', name: 'video game' },
  { emoji: '🕹️', name: 'joystick' },
  { emoji: '🎯', name: 'direct hit' },
  { emoji: '🏆', name: 'trophy' },
  { emoji: '⚡', name: 'high voltage' },
  { emoji: '🚀', name: 'rocket' },
  { emoji: '🌟', name: 'glowing star' },
  { emoji: '💎', name: 'gem stone' },
  { emoji: '🎲', name: 'game die' },
  { emoji: '🃏', name: 'joker' },
  { emoji: '🦸', name: 'superhero' },
  { emoji: '🦹', name: 'supervillain' },
  { emoji: '👻', name: 'ghost' },
  { emoji: '🎪', name: 'circus tent' },
  
  // Ninja & Martial Arts
  { emoji: '🥷', name: 'ninja' },
  { emoji: '⚔️', name: 'crossed swords' },
  { emoji: '🗡️', name: 'dagger' },
  { emoji: '🛡️', name: 'shield' },
  { emoji: '🏹', name: 'bow and arrow' },
  { emoji: '🥋', name: 'martial arts uniform' },
  { emoji: '👤', name: 'bust in silhouette' },
  { emoji: '🌙', name: 'crescent moon' },
  { emoji: '🌚', name: 'new moon face' },
  { emoji: '💨', name: 'dashing away' },
  { emoji: '⚡', name: 'lightning bolt' },
  { emoji: '🔥', name: 'fire' },
  { emoji: '💀', name: 'skull' },
  { emoji: '🖤', name: 'black heart' },
  
  // Tecnologia & Programação
  { emoji: '💻', name: 'laptop computer' },
  { emoji: '🖥️', name: 'desktop computer' },
  { emoji: '⌨️', name: 'keyboard' },
  { emoji: '🖱️', name: 'computer mouse' },
  { emoji: '💽', name: 'computer disk' },
  { emoji: '💾', name: 'floppy disk' },
  { emoji: '💿', name: 'optical disk' },
  { emoji: '📱', name: 'mobile phone' },
  { emoji: '📟', name: 'pager' },
  { emoji: '☎️', name: 'telephone' },
  { emoji: '📞', name: 'telephone receiver' },
  { emoji: '🔌', name: 'electric plug' },
  { emoji: '🔋', name: 'battery' },
  { emoji: '💡', name: 'light bulb' },
  { emoji: '🔦', name: 'flashlight' },
  { emoji: '📡', name: 'satellite antenna' },
  { emoji: '🛰️', name: 'satellite' },
  { emoji: '📺', name: 'television' },
  { emoji: '📻', name: 'radio' },
  { emoji: '⏰', name: 'alarm clock' },
  { emoji: '⌚', name: 'watch' },
  { emoji: '🧮', name: 'abacus' },
  { emoji: '🔧', name: 'wrench' },
  { emoji: '🔨', name: 'hammer' },
  { emoji: '⚙️', name: 'gear' },
  { emoji: '🛠️', name: 'hammer and wrench' },
  { emoji: '🔩', name: 'nut and bolt' },
  { emoji: '⚗️', name: 'alembic' },
  { emoji: '🧪', name: 'test tube' },
  { emoji: '🔬', name: 'microscope' },
  { emoji: '🔭', name: 'telescope' },
  { emoji: '📊', name: 'bar chart' },
  { emoji: '📈', name: 'chart increasing' },
  { emoji: '📉', name: 'chart decreasing' },
  
  // Símbolos & Códigos
  { emoji: '🔐', name: 'locked with key' },
  { emoji: '🔒', name: 'locked' },
  { emoji: '🔓', name: 'unlocked' },
  { emoji: '🔑', name: 'key' },
  { emoji: '🗝️', name: 'old key' },
  { emoji: '💳', name: 'credit card' },
  { emoji: '🏧', name: 'ATM sign' },
  { emoji: '🔢', name: 'input numbers' },
  { emoji: '🔣', name: 'input symbols' },
  { emoji: '🔤', name: 'input latin letters' },
  { emoji: '🔠', name: 'input latin uppercase' },
  { emoji: '🔡', name: 'input latin lowercase' },
  { emoji: '💯', name: 'hundred points' },
  { emoji: '🎊', name: 'confetti ball' },
  { emoji: '🎉', name: 'party popper' },
  
  // Internet & Redes
  { emoji: '🌐', name: 'globe with meridians' },
  { emoji: '📧', name: 'e-mail' },
  { emoji: '📨', name: 'incoming envelope' },
  { emoji: '📩', name: 'envelope with arrow' },
  { emoji: '📤', name: 'outbox tray' },
  { emoji: '📥', name: 'inbox tray' },
  { emoji: '📮', name: 'postbox' },
  { emoji: '💌', name: 'love letter' },
  { emoji: '📝', name: 'memo' },
  { emoji: '📄', name: 'page facing up' },
  { emoji: '📃', name: 'page with curl' },
  { emoji: '📑', name: 'bookmark tabs' },
  { emoji: '🔖', name: 'bookmark' },
  { emoji: '📋', name: 'clipboard' },
  { emoji: '📈', name: 'chart with upwards trend' },
  { emoji: '📉', name: 'chart with downwards trend' }
];